name: Deploy to AWS

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  terraform_deployment:
    name: AWS Terraform Deployment
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ENVIRONMENT: ${{ inputs.environment }}
      TF_BACKEND_S3_BUCKET: ${{ secrets.AWS_TERRAFORM_BACKEND_BUCKET }}
      TF_BACKEND_DYNAMODB_TABLE: ${{ secrets.AWS_TERRAFORM_BACKEND_DYNAMODB_TABLE }}
      REGION: ${{ secrets.AWS_REGION }}
      INFRA: ${{ vars.AWS_INFRA }}
      APP_NAME: ${{ vars.APP_NAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Python for Building Package
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv==2025.0.4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        working-directory: ./infra/terraform/aws
        run: |
          terraform init \
            -backend-config="bucket=${TF_BACKEND_S3_BUCKET}" \
            -backend-config="dynamodb_table=${TF_BACKEND_DYNAMODB_TABLE}" \
            -backend-config="region=${REGION}" \
            -backend-config=workspace_key_prefix=${APP_NAME}

          terraform workspace select -or-create "${ENVIRONMENT}"

      - name: Terraform Plan
        working-directory: ./infra/terraform/aws
        run: |
          terraform plan \
            -var="region=${REGION}" \
            -var="infra=${INFRA}" \
            -var="environment=${ENVIRONMENT}" \
            -var="app_name=${APP_NAME}" \
            -out=tfplan

      - name: Terraform Apply
        working-directory: ./infra/terraform/aws
        run: terraform apply -auto-approve tfplan
