name: Deploy FastAPI Service to GCP

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev|prod)'
        required: true
        default: 'dev'

jobs:
  lint_and_unit_tests:
    name: Pre-commit Lint and Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv==2025.0.4
          pipenv requirements --categories default,dev-packages > requirements.txt
          pip install -r requirements.txt

      - name: Run Pre-commit
        run: |
          pre-commit run --all-files

      - name: Run Pytest
        run: |
          ./run-unit-tests-with-coverage.sh

  terraform_deployment:
    name: Terraform Deployment
    needs: lint_and_unit_tests
    runs-on: ubuntu-latest
    env:
      GOOGLE_PROJECT_PREFIX: ${{ secrets.GCP_PREFIX }}
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_DEPLOYER_KEY }}
      TF_BACKEND_GCS_BUCKET: ${{ secrets.TF_BACKEND_GCS_BUCKET }}
      ENVIRONMENT: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv==2025.0.4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Set up Terraform Workspace
        run: |
          terraform workspace select -or-create ${ENVIRONMENT}

      - name: Terraform Init
        run: |
          terraform init --backend-config="bucket=${TF_BACKEND_GCS_BUCKET}"
